---

env:
  global:
    - REPO=loganmarchione/docker-iperf3

services:
  - docker

script:
  # Build the container
  - docker build --tag ${REPO} .

  # Test if the container runs
  - docker run --name test-container --detach --publish '5201:5201' ${REPO}
  - sleep 10
  - docker exec --tty test-container /bin/sh -c "which iperf3 && iperf3 --version"
