version: '3'
services:
  iperf3:
    container_name: docker-iperf3
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - iperf3
    ports:
      - '5201:5201'

networks:
  iperf3: