name: Test

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: "0 5 * * 0"

env:
  USER: loganmarchione
  REPO: docker-iperf3

jobs:
  build_ubuntu:
    name: Build Ubuntu

    runs-on: ubuntu-latest
    env:
      BASE: ubuntu

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v2

    - name: Build the image
      run: |
        echo "VERSION=$(cat VERSION)" >> $GITHUB_ENV
        docker build --file ${BASE}/Dockerfile --tag ${USER}/${REPO}:${VERSION} .

    - name: Test container
      run: |
        docker run --name test-container --detach --publish '5201:5201' ${USER}/${REPO}:${VERSION}
        sleep 10
        docker ps -a
        docker exec --tty test-container /bin/sh -c "which iperf3 && iperf3 --version"

  build_alpine:
    name: Build Alpine

    runs-on: ubuntu-latest
    env:
      BASE: alpine

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v2
        
