name: Test

on:
  push:
    branches:
      - master
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
  schedule:
    - cron: "0 5 * * 0"

env:
  USER: loganmarchione
  REPO: docker-iperf3

jobs:
  ubuntu:
    name: Build and test (Ubuntu base)

    runs-on: ubuntu-latest
    env:
      BASE: ubuntu

    steps:
    - name: Check out the codebase
      uses: actions/checkout@v2

    - name: Set variables
      run: |
        VER=$(cat VERSION)
        echo "VERSION=$VER" >> $GITHUB_ENV
        echo $VERSION

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ${BASE}/Dockerfile
        load: true
        tags: |
          ${USER}/${REPO}:${VERSION}
          ${USER}/${REPO}:latest

    - name: Test image
      run: |
        docker run --name test-container --detach --publish '5201:5201' ${USER}/${REPO}:${VERSION}
        docker ps -a
        docker exec --tty test-container /bin/sh -c "which iperf3 && iperf3 --version"
